// <auto-generated />
using System;
using Garage_2._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage_2._0.Migrations
{
    [DbContext(typeof(Garage_2_0Context))]
    [Migration("20220714091125_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Garage_2._0.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("NrOfWheels")
                        .HasColumnType("int");

                    b.Property<int>("ParkingLot")
                        .HasColumnType("int");

                    b.Property<string>("RegNr")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("TimeOfArrival")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Silver",
                            Make = "Volvo",
                            Model = "V70",
                            NrOfWheels = 4,
                            ParkingLot = 1,
                            RegNr = "ABC123",
                            TimeOfArrival = new DateTime(2022, 7, 14, 11, 11, 25, 744, DateTimeKind.Local).AddTicks(7040),
                            VehicleType = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "Red",
                            Make = "Saab",
                            Model = "95",
                            NrOfWheels = 4,
                            ParkingLot = 2,
                            RegNr = "DEF456",
                            TimeOfArrival = new DateTime(2022, 7, 14, 11, 11, 25, 744, DateTimeKind.Local).AddTicks(7045),
                            VehicleType = 1
                        },
                        new
                        {
                            Id = 3,
                            Color = "Green",
                            Make = "Ford",
                            Model = "Mustang",
                            NrOfWheels = 4,
                            ParkingLot = 3,
                            RegNr = "GHI789",
                            TimeOfArrival = new DateTime(2022, 7, 14, 11, 11, 25, 744, DateTimeKind.Local).AddTicks(7049),
                            VehicleType = 1
                        },
                        new
                        {
                            Id = 4,
                            Color = "Black",
                            Make = "Harley-Davidson",
                            Model = "Pan America",
                            NrOfWheels = 2,
                            ParkingLot = 4,
                            RegNr = "JKL891",
                            TimeOfArrival = new DateTime(2022, 7, 14, 11, 11, 25, 744, DateTimeKind.Local).AddTicks(7054),
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 5,
                            Color = "Orange",
                            Make = "Scania",
                            Model = "XT",
                            NrOfWheels = 6,
                            ParkingLot = 5,
                            RegNr = "MNO345",
                            TimeOfArrival = new DateTime(2022, 7, 14, 11, 11, 25, 744, DateTimeKind.Local).AddTicks(7058),
                            VehicleType = 2
                        },
                        new
                        {
                            Id = 6,
                            Color = "Yellow",
                            Make = "Scania",
                            Model = "zzz",
                            NrOfWheels = 6,
                            ParkingLot = 6,
                            RegNr = "PQR912",
                            TimeOfArrival = new DateTime(2022, 7, 14, 11, 11, 25, 744, DateTimeKind.Local).AddTicks(7062),
                            VehicleType = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
